version: "3.8"
services:
  ghost:
    image: ghost:latest
    container_name: ghost-local
    ports:
      - "2368:2368"
    environment:
      url: http://localhost:2368
      NODE_ENV: development # 테마 변경을 즉시 반영
    volumes:
      - ./content:/var/lib/ghost/content
      - ./theme:/var/lib/ghost/content/themes/sipe-team-blog-theme
